#
# Makefile
# greennewbie, 2021-05-22 16:10
#

objects = main.o BinarySearch.o

exe : $(objects)
	g++ -o exe $(objects)


BinarySearch.o : BinarySearch.h

main.o : BinarySearch.h

clean :
	rm exe *.o
# vim:ft=make
#
